# Generated by Django 2.2.6 on 2019-10-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soccer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ManyToManyField(related_name='_match_team1_+', to='Soccer.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ManyToManyField(related_name='_match_team2_+', to='Soccer.Player'),
        ),
    ]
