# Generated by Django 2.2.6 on 2019-10-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soccer', '0002_auto_20191025_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ManyToManyField(related_name='team1', to='Soccer.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ManyToManyField(related_name='team2', to='Soccer.Player'),
        ),
    ]
