# Generated by Django 2.2.6 on 2019-10-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soccer', '0003_auto_20191025_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.DecimalField(decimal_places=10, max_digits=14)),
                ('mu', models.DecimalField(decimal_places=10, max_digits=12)),
                ('sigma', models.DecimalField(decimal_places=10, max_digits=11)),
                ('mse', models.DecimalField(decimal_places=10, max_digits=11)),
                ('player', models.ForeignKey(on_delete='CASCADE', to='Soccer.Player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='rating',
            field=models.ManyToManyField(related_name='match', to='Soccer.Rating'),
        ),
    ]
