# Generated by Django 2.2.6 on 2019-10-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soccer', '0004_auto_20191027_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='elo',
            field=models.DecimalField(decimal_places=10, default=1200.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='rating',
            name='mse',
            field=models.DecimalField(decimal_places=10, default=0.5, max_digits=11),
        ),
        migrations.AlterField(
            model_name='rating',
            name='mu',
            field=models.DecimalField(decimal_places=10, default=25.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='rating',
            name='sigma',
            field=models.DecimalField(decimal_places=10, default=8.333333333333334, max_digits=11),
        ),
    ]
