# Generated by Django 2.2.6 on 2019-10-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soccer', '0005_auto_20191027_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='player',
            field=models.ForeignKey(on_delete='CASCADE', related_name='ratings', to='Soccer.Player'),
        ),
    ]
